language: python

python:
    - '2.7'
    - '3.5'
    - '3.6'

# whitelist
branches:
    only:
        - master

script:
    - py.test pandascharm.py --pep8
    - coverage run -m py.test
    - coverage report --omit test_*.py

after_success:
  - codecov
