language: python

python:
    - '2.7'
    - '3.5'
    - '3.6'

# whitelist
branches:
    only:
        - master

install:
    - pip install .
    - pip install pycodestyle
    - pip install pytest
    - pip install coverage
    - pip install codecov
    - pip install dendropy
    - pip install biopython

script:
    - pycodestyle pandascharm.py test_pandascharm.py setup.py
    - coverage run -m pytest test_pandascharm.py
    - coverage report -m pandascharm.py

after_success:
  - codecov
