language: python

python:
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'

# whitelist
branches:
    only:
        - master

script:
    pep8 pandascharm.py
    py.test --cov=pandascharm.py

after_success:
  - codecov
