language: python

python:
    - '2.7'
    - '3.5'
    - '3.6'

# whitelist
branches:
    only:
        - master

script:
    - py.test pandascharm.py --pep8
    - coverage run -m py.test
    - coverage report --include pandascharm.py -m

after_success:
  - codecov
