language: python

python:
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'

# whitelist
branches:
    only:
        - master

script:
    py.test --pep8
    coverage run -m py.test
    coverage report --include test_*.py

after_success:
  - codecov
